name: Deploy Frontend

on: 
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.STATIC_WEBSITE_STORAGE_ACCOUNT_NAME }} \
            --auth-mode key \
            --overwrite=true \
            --destination '$web' \
            --source frontend/

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge \
            --content-paths  "/*" \
            --profile-name ${{ secrets.CDN_PROFILE_NAME }} \
            --name ${{ secrets.CDN_PROFILE_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}

      - name: Azure logout
        run: az logout
        if: always()
